name: toadie
dependencies:
- openssl=1.0.2f=0
- pip=8.0.2=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=19.6.2=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - babel==2.2.0
  - boto3==1.2.3
  - botocore==1.3.26
  - click==6.2
  - colorama==0.3.6
  - debtcollector==1.3.0
  - docutils==0.12
  - honcho==0.6.6
  - iso8601==0.1.11
  - jmespath==0.9.0
  - jsonpatch==1.13
  - jsonpointer==1.10
  - keystoneauth1==2.2.0
  - monotonic==0.6
  - msgpack-python==0.4.7
  - netaddr==0.7.18
  - netifaces==0.10.4
  - oslo.i18n==3.3.0
  - oslo.serialization==2.3.0
  - oslo.utils==3.5.0
  - pbr==1.8.1
  - prettytable==0.7.2
  - pykube==0.7.1
  - python-dateutil==2.4.2
  - python-novaclient==3.2.0
  - pytz==2015.7
  - pyyaml==3.11
  - requests==2.9.1
  - simplejson==3.8.1
  - six==1.10.0
  - stevedore==1.11.0
  - toadie (/Volumes/biggiexsmalls/ZIFF/toadie)==0.1.0
  - wrapt==1.10.6

