package:
    name: toadie
    version: "0.1.0a1"

source:
    git_url: https://github.com/dgonzo/toadie.git

requirements:
    build:
        - python
        - setuptools
        - click
    run:
        - python

about:
    home: https://github.com/dgonzo/toadie.git
    license: APACHE

